### ISSUE TITLE
Allow to add custom names of evolutions

### ISSUE THREAD

**Issue by igorkamyshev** [igorkamyshev/trona#209]
Like `1-init.sql`, `2-add-user.sql`, etc.

**Comment by uka17** [comment]
What is the exact migration file naming convention? Just `x-description.sql`?
As a proposal, it can be `x[.y]-description.sql`:
- `x` and `y` - numbers (`y` is optional)
- `description` - text

Following order considers both `x` and `y`, moreover `y` should be considered as a subset of `x`. This will allow to insert additional scripts into migration sequence row.
Examples:
```
1-create-customer-table.sql
1.1-alter-customer-table.sql
1.2-alter-again-customer-table.sql
1.3-add-column-customer-table.sql
2-remove-column-customer-table.sql
3-truncate-customer-table.sql
4-drop-customer-table.sql
4.1-create-customer-table.sql
```
This one also should work:
```
1-create-customer-table.sql
2-remove-column-customer-table.sql
3-truncate-customer-table.sql
```
...and this one:
```
1-create-customer-table.sql
1.3-add-column-customer-table.sql
2-remove-column-customer-table.sql
3-truncate-customer-table.sql
4-drop-customer-table.sql
4.1-create-customer-table.sql
```
This one doesn't:
```
a-create-customer-table.sql
1.3-add-column-customer-table.sql
2-remove-column-customer-table.sql
3-truncate-customer-table.sql
4-drop-customer-table.sql
4.1-create-customer-table.sql
```
...throws error "Unable to determine evolution order for a-create-customer-table.sql file"

**Comment by igorkamyshev** [comment]
In my opinion, we should stay simple. So, I prefer convention x.description.sql or something like this, without additional numbers and errors of order determining.
